Repository pluginsGLPI/formcreator, pull requests merged in 2018-12, with the labels that each got.

#1223 Add search option
  inc/form_answer.class.php
Labels: feature

#1227 Choose a root ticket category for display
  inc/fields/dropdownfield.class.php
  inc/question.class.php
  tests/suite-unit/PluginFormcreatorDropdownField.php
Labels: feature

#1239 Default value of urgency field
  inc/fields/urgencyfield.class.php
  inc/question.class.php
  tests/suite-integration/PluginFormcreatorTargetTicket.php
Labels: bug

#1240 9.4-9.3/compat
  .travis.yml
  front/formdisplay.php
  front/targetchange.form.php
  front/targetticket.form.php
  hook.php
  inc/category.class.php
  inc/common.class.php
  inc/composite.class.php
  inc/fields/dropdownfield.class.php
  inc/fields/tagfield.class.php
  inc/form.class.php
  inc/formanswer.class.php
  inc/issue.class.php
  inc/question.class.php
  inc/question_condition.class.php
  inc/section.class.php
  inc/target.class.php
  inc/targetbase.class.php
  inc/targetchange.class.php
  inc/targetticket.class.php
  inc/wizard.class.php
  install/install.php
  install/upgrade_to_2.5.php
  install/upgrade_to_2.6.php
  setup.php
  tests/bootstrap.php
  tests/suite-integration/PluginFormcreatorForm.php
  tests/suite-integration/PluginFormcreatorSection.php
  tests/suite-integration/PluginFormcreatorTargetTicket.php
  tests/suite-uninstall/Config.php
  tests/suite-unit/PluginFormcreatorCategory.php
  tests/suite-unit/PluginFormcreatorForm.php
  tests/suite-unit/PluginFormcreatorSection.php
Labels: task

#1234 Reorder upgrade phases
  install/upgrade_to_2.7.php
Labels: bug
