Repository pluginsGLPI/formcreator, pull requests merged in 2018-11, with the labels that each got.

#1178 Textarea rendering
  inc/fields/textareafield.class.php
  inc/form_answer.class.php
  inc/targetchange.class.php
Labels: bug

#1181 Entity from a question
  inc/targetchange.class.php
Labels: bug

#1174 Add search option to get assign group / tech to ticket
  hook.php
  inc/issue.class.php
Labels: feature, wip

#1184 Changes don't support template
  install/mysql/plugin_formcreator_empty.sql
  install/update_2.6_2.7.php
Labels: bug

#1191 Redirect to service catalog when viewing ticket
  setup.php
Labels: bug

#1219 Refactor rich rendering for fields and target templates
  inc/fieldinterface.class.php
  inc/fields/actorfield.class.php
  inc/fields/checkboxesfield.class.php
  inc/fields/datefield.class.php
  inc/fields/datetimefield.class.php
  inc/fields/descriptionfield.class.php
  inc/fields/dropdownfield.class.php
  inc/fields/emailfield.class.php
  inc/fields/filefield.class.php
  inc/fields/floatfield.class.php
  inc/fields/hiddenfield.class.php
  inc/fields/hostnamefield.class.php
  inc/fields/integerfield.class.php
  inc/fields/ipfield.class.php
  inc/fields/multiselectfield.class.php
  inc/fields/radiosfield.class.php
  inc/fields/selectfield.class.php
  inc/fields/textareafield.class.php
  inc/fields/textfield.class.php
  inc/fields/urgencyfield.class.php
  inc/form_answer.class.php
  inc/targetbase.class.php
  inc/targetchange.class.php
  inc/targetticket.class.php
  tests/suite-unit/PluginFormcreatorActorField.php
  tests/suite-unit/PluginFormcreatorDatetimeField.php
Labels: bug

#1206 fix(QuestionCondition): inconsistency in selectors
  inc/field.class.php
  inc/fields.class.php
  js/scripts.js.php
Labels: bug

#1153 Search engine and accented chars
  inc/common.class.php
  inc/form.class.php
Labels: bug, need feedback
