Repository pluginsGLPI/formcreator, pull requests merged in 2018-08, with the labels that each got.

#1055 Check access only when a user is logged in
  front/formdisplay.php
Labels: bug

#1056 Fix creation of conditions
  ajax/question_condition.php
Labels: bug

#1060 Description displayed in italic
  css/styles.css
Labels: bug

#1066 fix names of users from actors in generated tickets
  inc/fields/actorfield.class.php
Labels: bug

#1075 l10n – added Czech translation into xml data
  plugin.xml
Labels: documentation

#1077 Fix warnings
  inc/wizard.class.php
Labels: bug

#1004 WIP Limit assets dropdowns to my assets
  inc/fields/dropdownfield.class.php
Labels: feature

#1078 Hostname field
  inc/fields/hostnamefield.class.php
  pics/ui-hostname-field.png
Labels: feature

#1079 Handle rich text mode for GLPI 9.4
  inc/fields/checkboxesfield.class.php
  inc/fields/multiselectfield.class.php
  inc/issue.class.php
  inc/targetbase.class.php
  inc/targetchange.class.php
Labels: feature

#1083 fix(form): php warning
  inc/form.class.php
Labels: bug
