Repository pluginsGLPI/formcreator, pull requests merged in 2019-02, with the labels that each got.

#1285 Single quote not escaped
  inc/targetticket.class.php
Labels: bug

#1290 Quote issue in javascript code
  js/scripts.js.php
Labels: bug

#1292 fix escaping of form name when inserting formanswer
  inc/formanswer.class.php
Labels: bug

#1300 Category not assigned
  inc/targetbase.class.php
  inc/targetchange.class.php
  inc/targetticket.class.php
  tests/src/PluginFormcreatorTargetChangeDummy.php
  tests/src/PluginFormcreatorTargetTicketDummy.php
  tests/suite-unit/PluginFormcreatorTargetChange.php
  tests/suite-unit/PluginFormcreatorTargetTicket.php
Labels: bug

#1326 Add Project in the supported list
  inc/question.class.php
Labels: feature

#1325 build: bump version
  install/install.php
  install/upgrade_to_2.9.php
  setup.php
Labels: task

#1313 Bad subtree handling for ITIL category
  inc/fields/dropdownfield.class.php
Labels: bug

#1305 Add qtip for ticket types
  inc/fields/dropdownfield.class.php
  inc/fields/urgencyfield.class.php
  inc/formanswer.class.php
  inc/issue.class.php
  inc/targetbase.class.php
Labels: feature
