Repository pluginsGLPI/formcreator, pull requests merged in 2022-03, with the labels that each got.

#2626 Add form headers hook
  inc/form.class.php
  inc/formanswer.class.php
  templates/pages/userform.html.twig
Labels: feature

#2624 Update menu icons to Tabler-Icons
  inc/common.class.php
  inc/issue.class.php
  tests/3-unit/PluginFormcreatorCommon.php
  tests/3-unit/PluginFormcreatorIssue.php
Labels: feature

#2650 Null not alowed fir requesters_id
  inc/issue.class.php
Labels: bug

#2659 Simplify sync issue
  inc/issue.class.php
Labels: enhancement

#2662 Single click to toggle default form flag
  ajax/form.php
  inc/form.class.php
  js/scripts.js
Labels: enhancement

#2625 Add form visiblity hooks
  inc/form.class.php
Labels: feature

#2664 Better template support for request source (2.13)
  inc/targetticket.class.php
  install/mysql/plugin_formcreator_empty.sql
  install/upgrade_to_2.12.5.php
  install/upgrade_to_2.13.php
  tests/3-unit/PluginFormcreatorTargetTicket.php
  tests/src/PluginFormcreatorTargetTicketDummy.php
Labels: feature
