Repository pluginsGLPI/formcreator, pull requests merged in 2022-09, with the labels that each got.

#2974 Form_Profile: Fix PHPDOC / undefined session value
  inc/form_profile.class.php
Labels: bug

#2972 feat(kb): preselect see all categorie
  js/scripts.js
Labels: enhancement

#2973 feat(core): add new option for category visibility
  inc/entityconfig.class.php
  inc/form.class.php
  install/install.php
  install/mysql/plugin_formcreator_2.14.0_empty.sql
  install/upgrade_to_2.14.php
  tests/1-install/Config.php
  tests/3-unit/PluginFormcreatorEntityConfig.php
Labels: enhancement

#2989 feat(core): add new option to fold / unfold left menu
  inc/common.class.php
  inc/entityconfig.class.php
  install/install.php
  install/mysql/plugin_formcreator_2.14.0_empty.sql
  install/upgrade_to_2.14.php
  tests/1-install/Config.php
  tests/3-unit/PluginFormcreatorEntityConfig.php
Labels: enhancement

#2999 Email addresses were ignored
  inc/abstractitiltarget.class.php
Labels: bug, need feedback

#3004 Fix submit for forms without targets
  ajax/formanswer.php
Labels: bug
