Repository pluginsGLPI/formcreator, pull requests merged in 2022-11, with the labels that each got.

#3061 fix(dashboard): fix dashboard height
  inc/common.class.php
Labels: bug

#3070 Prevent sending two csrf tokens
  js/scripts.js
Labels: bug

#3082 fix broken Support for sla and ola from question
  inc/field/dropdownfield.class.php
  templates/field/dropdownfield.html.twig
Labels: bug

#3090 Prevent warning on null value
  inc/formanswer.class.php
Labels: bug

#3092 Show save button for followup edit in simplified service catalog
  inc/issue.class.php
Labels: bug, need feedback

#3093 More hooks
  inc/abstractfield.class.php
  inc/abstractitiltarget.class.php
  inc/plugintargetinterface.class.php
  inc/target_actor.class.php
  js/scripts.js
Labels: enhancement
