Repository pluginsGLPI/formcreator, pull requests merged in 2023-06, with the labels that each got.

#3293 SQL error for GLPI objects / tickets and some specific rights
  inc/field/dropdownfield.class.php
Labels: bug

#3285 Bad question id in section condition
  inc/condition.class.php
Labels: bug

#3306 fix: resize dashboard to match GLPI's core
  inc/common.class.php
  install/upgrade_to_2.13.7.php
Labels: bug

#3307 Php warnings anonymization
  inc/issue.class.php
Labels: bug, need feedback

#3308 show mandatory field
  inc/question.class.php
  templates/field/fieldsfield.html.twig
Labels: feature
