Repository pluginsGLPI/formcreator, pull requests merged in 2023-01, with the labels that each got.

#3133 Newline
  inc/formanswer.class.php
Labels: bug

#3117 Default value not displayed
  inc/field/checkboxesfield.class.php
Labels: need feedback

#3115 Form access check
  inc/form.class.php
Labels: bug, need feedback

#3140 Multiple tag questions set but not displayed in designer
  inc/abstractitiltarget.class.php
  inc/question.class.php
Labels: bug

#3125 Follow entity change on ticket transfer
  hook.php
  setup.php
Labels: need feedback

#3147 fix(composite): ignore link to non existing ticket
  inc/composite.class.php
Labels: bug

#3144 fix (form): Invalid event target and debouncing
  js/scripts.js
Labels: bug

#3138 include answers with multi ticket for actor filter
  hook.php
  inc/formanswer.class.php
  inc/issue.class.php
Labels: enhancement, need feedback

#3155 Allow more itemtypes to associated elements
  inc/targetticket.class.php
  tests/3-unit/PluginFormcreatorTargetTicket.php
Labels: bug
