Repository pluginsGLPI/formcreator, pull requests merged in 2023-05, with the labels that each got.

#3267 fix(clean_tickets command): Take merged tickets into account
  inc/command/cleanticketscommand.class.php
Labels: bug

#3226 Rebuild uploads for answer edition
  inc/field/filefield.class.php
Labels: bug, need feedback

#3261 Conditions don't work when not sanitized
  install/upgrade_to_2.13.6.php
Labels: bug, need feedback

#3238 Show contact field
  inc/field/dropdownfield.class.php
  inc/field/glpiselectfield.class.php
Labels: need feedback

#3258 Stronger upgrade for unsigned columns with non standard names
  install/install.php
Labels: need feedback
